# Generated by Django 2.2.11 on 2020-03-15 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_movements', to='games.Tile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_movements', to='games.Tile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='movement',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='unique_path'),
        ),
        migrations.AddConstraint(
            model_name='movement',
            constraint=models.CheckConstraint(check=models.Q(amount__gte=1), name='nonempty_amount'),
        ),
        migrations.AddConstraint(
            model_name='movement',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, source=django.db.models.expressions.F('target')), name='nonempty_distance'),
        ),
    ]
