# Generated by Django 2.2.11 on 2020-03-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200315_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tick',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
